import fs from 'node:fs';import test from 'node:test';import assert from 'node:assert/strict';
import {importWorkbook,analyze,detach,DetachError,LIMITS}from'../src/core.mjs';import{demoBytes,fixtureBytes}from'../src/fixture.mjs';import{readZip,writeZip,inspectZip}from'../src/zip.mjs';import{parseFormula,addressOf,columnName}from'../src/formula.mjs';
const wb=async sheets=>importWorkbook(await fixtureBytes(sheets));
const simple=async(formula,extra={})=>wb([{name:'Plan',cells:{A1:2,A2:3,A3:{formula},...extra}},{name:'Other',cells:{A1:5,A2:-2,A3:0,A4:.25}}]);
const issue=(workbook,keep,code)=>{const a=analyze(workbook,keep);assert.equal(a.ok,false,JSON.stringify(a));assert.equal(a.issues[0].code,code,JSON.stringify(a));assert.equal(a.ledger.length,0);assert.equal(a.preview.length,0);return a;};
const patch=async(bytes,part,fn)=>{const z=await readZip(bytes);z.set(part,fn(z.get(part)));return writeZip(z)};
test('seeded cached values are recomputed and exact exports preserve editable formulas',async()=>{const w=await importWorkbook(await demoBytes()),a=analyze(w,['Plan']);assert.equal(a.ok,true);assert.deepEqual(a.preview.map(x=>x.value),[46,10,56]);assert.deepEqual(a.preview.map(x=>x.after),['=B2*(6)+(-2)','=B3*(5)','=SUM(C2:C3)']);assert.equal(a.ledger.length,3);assert.deepEqual(a.ledger[0].lineage.map(x=>x.cell),['Derived!B2','Constants!B2']);const out=await detach(w,['Plan']);const r=await importWorkbook(out.xlsx);assert.deepEqual(r.sheets.map(s=>s.name),['Plan']);assert.equal(r.sheets[0].map.get('B2').value,8);assert.equal(r.sheets[0].map.get('C2').type,'formula');assert.equal(r.styles.raw,w.styles.raw);assert.deepEqual(analyze(r,['Plan']).preview.map(x=>x.value),[46,10,56]);assert.match(out.ledgerCsv,/'=B2/);});
test('acyclic omitted-to-kept backlink is blocked with exact path',async()=>{const w=await importWorkbook(await demoBytes({backlink:true}));const a=issue(w,['Plan'],'KEPT_BACKLINK');assert.deepEqual(a.issues[0].path,['Plan!C2','Derived!B2','Plan!B2']);await assert.rejects(detach(w,['Plan']),e=>e.code==='KEPT_BACKLINK');});
test('retaining dependent source sheet preserves quadratic response',async()=>{const w=await importWorkbook(await demoBytes({backlink:true}));const a=analyze(w,['Plan','Derived']);assert.equal(a.ok,true);assert.deepEqual(a.preview.filter(x=>x.sheet==='Plan').map(x=>x.value),[126,10,136]);assert.equal(a.preview.find(x=>x.cell==='C2').after,'=B2*Derived!$B$2+(-2)');const out=await importWorkbook((await detach(w,['Plan','Derived'])).xlsx);out.sheets[0].map.get('B2').value=10;out.sheets[0].map.get('B3').value=3;assert.deepEqual(analyze(out,['Plan','Derived']).preview.filter(x=>x.sheet==='Plan').map(x=>x.value),[198,15,213]);});
test('12 closed-form input states remain live after detachment',async()=>{const out=await importWorkbook((await detach(await importWorkbook(await demoBytes()),['Plan'])).xlsx);for(const x of[0,1,8,10])for(const y of[0,2,3]){out.sheets[0].map.get('B2').value=x;out.sheets[0].map.get('B3').value=y;const a=analyze(out,['Plan']);assert.deepEqual(a.preview.map(p=>p.value),[6*x-2,5*y,6*x+5*y-2]);}});
test('deterministic repeated exports',async()=>{const w=await importWorkbook(await demoBytes());const a=await detach(w,['Plan']),b=await detach(w,['Plan']);assert.deepEqual(a.xlsx,b.xlsx);assert.equal(a.ledgerCsv,b.ledgerCsv);assert.deepEqual(a.recipe,b.recipe)});
for(const [formula,value]of [['A1+Other!A1',7],['A1-Other!A2',4],['A1*Other!A2',-4],['A1/Other!A4',8],['-Other!A2',2],['+Other!A2',-2],['(A1+Other!A1)*A2',21],['Other!A1/Other!A1',1],['Other!A3+Other!A4',.25],['SUM(A1,A2,Other!A1)',10],['SUM(A1:A2)+Other!A1',10],['1e2+Other!A4',100.25],['.5*Other!A1',2.5],['  A1 + other!$a$1 ',7]])test('numeric AST '+formula,async()=>{const a=analyze(await simple(formula),['Plan']);assert.equal(a.ok,true,JSON.stringify(a));assert.equal(a.preview[0].value,value);const r=await importWorkbook((await detach(await simple(formula),['Plan'])).xlsx);assert.equal(analyze(r,['Plan']).preview[0].value,value)});
test('repeated references produce occurrence-specific ledger rows',async()=>{const a=analyze(await simple('Other!A1+Other!A1+Other!A1'),['Plan']);assert.equal(a.ledger.length,3);assert.deepEqual(a.ledger.map(x=>x.occurrence),[1,2,3]);assert.equal(a.preview[0].after,'=(5)+(5)+(5)')});
test('quoted apostrophe sheet names and absolute A1 references',async()=>{const w=await wb([{name:'Plan',cells:{A1:{formula:"'O''Brien notes'!$b$2*2"}}},{name:"O'Brien notes",cells:{B2:-.5}}]);assert.equal(analyze(w,['Plan']).preview[0].after,'=(-0.5)*2')});
test('Japanese sheet names',async()=>{const w=await wb([{name:'計画',cells:{A1:{formula:"'計算 元'!A1+単価!B2"}}},{name:'計算 元',cells:{A1:3}},{name:'単価',cells:{B2:4}}]);assert.equal(analyze(w,['計画']).preview[0].value,7)});
test('all kept references remain byte-for-byte formula text',async()=>{const w=await simple('  A1 + Other!$A$1  '),a=analyze(w,['Plan','Other']);assert.equal(a.preview[0].after,'=  A1 + Other!$A$1  ');assert.equal(a.ledger.length,0)});
test('kept cross-sheet numeric SUM range is retained',async()=>{const a=analyze(await simple('SUM(Other!A1:A4)'),['Plan','Other']);assert.equal(a.ok,true);assert.equal(a.preview[0].value,3.25);assert.equal(a.preview[0].after,'=SUM(Other!A1:A4)')});
test('omitted SUM can be recomputed when exposed only as scalar',async()=>{const w=await wb([{name:'Plan',cells:{A1:{formula:'Other!B1*2'}}},{name:'Other',cells:{A1:2,A2:3,B1:{formula:'SUM(A1:A2)'}}}]);const a=analyze(w,['Plan']);assert.equal(a.ok,true);assert.equal(a.preview[0].after,'=(5)*2')});
for(const [formula,code]of [['SUM(Other!A1:A4)','BOUNDARY_RANGE'],['A1:A2','RANGE_CONTEXT'],['SUM(A2:A1)','RANGE'],['SUM(A1:Other!A1)','RANGE_3D'],['A1/Other!A3','DIV_ZERO'],['A1+A9','BLANK_OPERAND'],['A1+Missing!A1','MISSING_SHEET'],['IF(A1,2,3)','FUNCTION'],['NOW()','FUNCTION'],['INDIRECT("A1")','UNSUPPORTED_FORMULA'],['1^2','UNSUPPORTED_FORMULA'],['"hello"','UNSUPPORTED_FORMULA'],['[book]Sheet!A1','UNSUPPORTED_FORMULA'],['SUM(A:A)','REFERENCE'],['NamedValue+1','REFERENCE'],['A1#','UNSUPPORTED_FORMULA'],['1&2','UNSUPPORTED_FORMULA'],['A1>2','UNSUPPORTED_FORMULA'],['SUM()','SUM_EMPTY'],['1e101','NUMERIC_LIMIT']])test('rejects '+formula,async()=>{issue(await simple(formula),['Plan'],code)});
test('text labels cannot be arithmetic operands',async()=>issue(await simple('B1+1',{B1:'2'}),['Plan'],'TEXT_OPERAND'));
test('literal = text stays text on export',async()=>{const w=await simple('A1+1',{B1:'=1+1'}),r=await importWorkbook((await detach(w,['Plan'])).xlsx);assert.equal(r.sheets[0].map.get('B1').value,'=1+1');assert.equal(r.sheets[0].map.get('B1').type,'string')});
test('direct cycle witness',async()=>{const a=issue(await simple('A3+1'),['Plan'],'CYCLE');assert.deepEqual(a.issues[0].path,['Plan!A3','Plan!A3'])});
test('indirect cross-sheet cycle witness',async()=>{const w=await wb([{name:'Plan',cells:{A1:{formula:'Other!A1'}}},{name:'Other',cells:{A1:{formula:'Plan!A1'}}}]);assert.equal(issue(w,['Plan'],'CYCLE').issues[0].path.length,3)});
test('long 1500-formula DAG computes without recursive dependency traversal',async()=>{const cells={A1:1};for(let i=2;i<=1501;i++)cells['A'+i]={formula:'A'+(i-1)+'+1'};const w=await wb([{name:'Plan',cells:{A1:{formula:'Other!A1501'}}},{name:'Other',cells}]);const a=analyze(w,['Plan']);assert.equal(a.ok,true);assert.equal(a.preview[0].value,1501);assert.equal(a.ledger[0].lineage.length,1501)});
test('unsupported omitted formula blocks instead of dropping content',async()=>{const w=await wb([{name:'Plan',cells:{A1:1}},{name:'Other',cells:{A1:{formula:'RAND()'}}}]);issue(w,['Plan'],'FUNCTION')});
test('invalid selection blocked',async()=>{const w=await simple('A1+1');issue(w,[],'SELECTION');issue(w,['Unknown'],'SELECTION');assert.equal(analyze(w,['pLaN']).ok,true)});
for(const [name,part,modify,code]of [
 ['external package','xl/externalLinks/externalLink1.xml',()=>'<x/>','PACKAGE_FEATURE'],
 ['chart part','xl/charts/chart1.xml',()=>'<x/>','PACKAGE_FEATURE'],
 ['macro part','xl/vbaProject.bin',()=>'', 'PACKAGE_FEATURE'],
 ['data validations','xl/worksheets/sheet1.xml',s=>s.replace('</worksheet>','<dataValidations/></worksheet>'),'FEATURE'],
 ['conditional formatting','xl/worksheets/sheet1.xml',s=>s.replace('</worksheet>','<conditionalFormatting/></worksheet>'),'FEATURE'],
 ['hidden sheet','xl/workbook.xml',s=>s.replace('name="Plan"','name="Plan" state="hidden"'),'HIDDEN_SHEET'],
 ['defined name','xl/workbook.xml',s=>s.replace('</workbook>','<definedNames><definedName name="Foo">Plan!A1</definedName></definedNames></workbook>'),'DEFINED_NAMES'],
 ['1904 system','xl/workbook.xml',s=>s.replace('<sheets>','<workbookPr date1904="1"/><sheets>'),'DATE_SYSTEM'],
 ['shared formula','xl/worksheets/sheet1.xml',s=>s.replace('<f>','<f t="shared" si="0">'),'FORMULA_FEATURE'],
 ['array formula','xl/worksheets/sheet1.xml',s=>s.replace('<f>','<f t="array">'),'FORMULA_FEATURE'],
 ['boolean','xl/worksheets/sheet1.xml',s=>s.replace('r="B2" s="2"','r="B2" s="2" t="b"'),'CELL_TYPE'],
 ['date typed','xl/worksheets/sheet1.xml',s=>s.replace('r="B2" s="2"','r="B2" s="2" t="d"'),'CELL_TYPE'],
 ['DTD','xl/workbook.xml',s=>'<!DOCTYPE workbook [<!ENTITY x "oops">]>'+s,'XML'],
 ['external rel','xl/_rels/workbook.xml.rels',s=>s.replace('Id="rId1"','Id="rId1" TargetMode="External"'),'RELATIONSHIP']
])test('XLSX profile rejects '+name,async()=>{const bytes=await patch(await demoBytes(),part,modify);await assert.rejects(importWorkbook(bytes),e=>e instanceof DetachError&&e.code===code)});
test('date-formatted numeric operand is blocked',async()=>{const bytes=await patch(await demoBytes(),'xl/styles.xml',s=>s.replace('numFmtId="2"','numFmtId="14"'));issue(await importWorkbook(bytes),['Plan'],'DATE_OPERAND')});
test('source workbook DOM and source bytes unchanged by detach',async()=>{const source=await demoBytes(),w=await importWorkbook(source),original=JSON.stringify(w.sheets.map(s=>s.root));await detach(w,['Plan']);assert.equal(JSON.stringify(w.sheets.map(s=>s.root)),original);assert.deepEqual(source,await demoBytes())});
test('ZIP rejects arbitrary input and trailing bytes',async()=>{await assert.rejects(importWorkbook(new Uint8Array([1,2,3])),e=>e.code==='ZIP');const b=await demoBytes(),p=new Uint8Array(b.length+1);p.set(b);assert.throws(()=>inspectZip(p),e=>e.code==='ZIP')});
test('sheet and cell limits',async()=>{await assert.rejects(wb(Array.from({length:21},(_,i)=>({name:'S'+i,cells:{A1:1}}))),e=>e.code==='SHEET_LIMIT');const cells={};for(let i=1;i<=10001;i++)cells[columnName(i)+'1']=i;await assert.rejects(wb([{name:'Plan',cells}]),e=>e.code==='CELL_LIMIT')});
test('formula limit',async()=>{const cells={};for(let i=1;i<=2001;i++)cells['A'+i]={formula:'1+1'};await assert.rejects(wb([{name:'Plan',cells}]),e=>e.code==='FORMULA_LIMIT')});
test('range size and formula length are bounded',()=>{assert.throws(()=>parseFormula('1'.repeat(8193)),e=>e.code==='FORMULA_SIZE');assert.throws(()=>addressOf('XFE1'),e=>e.code==='REFERENCE');assert.throws(()=>addressOf('A1048577'),e=>e.code==='REFERENCE')});
test('elapsed time number format is rejected as operand',async()=>{const bytes=await patch(await demoBytes(),'xl/styles.xml',s=>s.replace('<fonts','<numFmts count="1"><numFmt numFmtId="164" formatCode="[h]"/></numFmts><fonts').replace('numFmtId="2"','numFmtId="164"'));issue(await importWorkbook(bytes),['Plan'],'DATE_OPERAND')});
test('inherited date style is rejected as operand',async()=>{const bytes=await patch(await demoBytes(),'xl/styles.xml',s=>s.replace('<cellStyleXfs count="1"><xf numFmtId="0"','<cellStyleXfs count="1"><xf numFmtId="14"'));issue(await importWorkbook(bytes),['Plan'],'DATE_OPERAND')});
test('large left associative AST does not recurse during evaluation',async()=>{const a=analyze(await simple(Array(2500).fill('1').join('+')),['Plan']);assert.equal(a.ok,true);assert.equal(a.preview[0].value,2500)});
test('precision-as-displayed, iterative and R1C1 modes reject',async()=>{for(const attribute of ['fullPrecision="0"','fullPrecision="false"','iterate="1"','refMode="R1C1"']){const bytes=await patch(await demoBytes(),'xl/workbook.xml',s=>s.replace('<calcPr ',`<calcPr ${attribute} `));await assert.rejects(importWorkbook(bytes),e=>e.code==='CALCULATION_MODE')}});
test('unlisted allowed-path worksheet rejects',async()=>{const bytes=await patch(await demoBytes(),'xl/worksheets/sheet99.xml',()=>'<worksheet/>');await assert.rejects(importWorkbook(bytes),e=>['PACKAGE','CONTENT_TYPE'].includes(e.code))});
test('duplicate workbook containers cannot hide unsupported features',async()=>{const bytes=await patch(await demoBytes(),'xl/workbook.xml',s=>s.replace('</workbook>','<definedNames/><definedNames><definedName name="HiddenName">Constants!B2</definedName></definedNames></workbook>'));await assert.rejects(importWorkbook(bytes),e=>e.code==='FEATURE')});
test('duplicate worksheet containers reject',async()=>{const bytes=await patch(await demoBytes(),'xl/worksheets/sheet1.xml',s=>s.replace('</worksheet>','<cols/></worksheet>'));await assert.rejects(importWorkbook(bytes),e=>e.code==='FEATURE')});
test('row-inherited date style blocks operand',async()=>{let bytes=await patch(await demoBytes(),'xl/styles.xml',s=>s.replace('numFmtId="2"','numFmtId="14"'));bytes=await patch(bytes,'xl/worksheets/sheet1.xml',s=>s.replace('r="B2" s="2"','r="B2"').replace('<row r="2"','<row r="2" s="2" customFormat="1"'));issue(await importWorkbook(bytes),['Plan'],'DATE_OPERAND')});
test('column-inherited date style blocks operand',async()=>{let bytes=await patch(await demoBytes(),'xl/styles.xml',s=>s.replace('numFmtId="2"','numFmtId="14"'));bytes=await patch(bytes,'xl/worksheets/sheet1.xml',s=>s.replace('r="B2" s="2"','r="B2"').replace('<col min="2"','<col style="2" min="2"'));issue(await importWorkbook(bytes),['Plan'],'DATE_OPERAND')});
test('foreign descendant namespace rejects',async()=>{const bytes=await patch(await demoBytes(),'xl/worksheets/sheet1.xml',s=>s.replace('<sheetData>','<sheetData xmlns="urn:foreign">'));await assert.rejects(importWorkbook(bytes),e=>e.code==='XML')});
test('workbook relationship namespace cannot be rebound',async()=>{const bytes=await patch(await demoBytes(),'xl/workbook.xml',s=>s.replace('xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"','xmlns:r="urn:foreign"'));await assert.rejects(importWorkbook(bytes),e=>e.code==='XML')});
test('legacy evaluation true lexical form rejects',async()=>{for(const attr of ['transitionEvaluation','transitionEntry','filterMode']){const bytes=await patch(await demoBytes(),'xl/worksheets/sheet1.xml',s=>s.replace('<sheetViews>',`<sheetPr ${attr}="true"/><sheetViews>`));await assert.rejects(importWorkbook(bytes),e=>e.code==='FEATURE')}});
test('wrong workbook MIME rejects',async()=>{const bytes=await patch(await demoBytes(),'[Content_Types].xml',s=>s.replace('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml','application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml'));await assert.rejects(importWorkbook(bytes),e=>e.code==='CONTENT_TYPE')});
test('missing worksheet manifest rejects',async()=>{const bytes=await patch(await demoBytes(),'[Content_Types].xml',s=>s.replace(/<Override PartName="\/xl\/worksheets\/sheet1.xml"[^>]*\/>/,''));await assert.rejects(importWorkbook(bytes),e=>e.code==='CONTENT_TYPE')});
test('optional theme must have exact content type and relationship and valid XML',async()=>{const d='http://schemas.openxmlformats.org/officeDocument/2006/relationships/';let bytes=await patch(await demoBytes(),'xl/theme/theme1.xml',()=> 'not XML');bytes=await patch(bytes,'[Content_Types].xml',s=>s.replace('</Types>','<Override PartName="/xl/theme/theme1.xml" ContentType="application/vnd.openxmlformats-officedocument.theme+xml"/></Types>'));await assert.rejects(importWorkbook(bytes),e=>e.code==='RELATIONSHIP');bytes=await patch(bytes,'xl/_rels/workbook.xml.rels',s=>s.replace('</Relationships>',`<Relationship Id="theme" Type="${d}theme" Target="theme/theme1.xml"/></Relationships>`));await assert.rejects(importWorkbook(bytes),e=>e.code==='XML');});
test('valid plain DrawingML theme is preserved',async()=>{let bytes=await patch(await demoBytes(),'xl/theme/theme1.xml',()=>fs.readFileSync(new URL('../fixtures/default-theme.xml',import.meta.url),'utf8'));bytes=await patch(bytes,'[Content_Types].xml',s=>s.replace('</Types>','<Override PartName="/xl/theme/theme1.xml" ContentType="application/vnd.openxmlformats-officedocument.theme+xml"/></Types>'));bytes=await patch(bytes,'xl/_rels/workbook.xml.rels',s=>s.replace('</Relationships>','<Relationship Id="theme" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme" Target="theme/theme1.xml"/></Relationships>'));const w=await importWorkbook(bytes),z=await readZip((await detach(w,['Plan'])).xlsx);assert.equal(z.get('xl/theme/theme1.xml'),w.files.get('xl/theme/theme1.xml'))});
test('mismatched style relationship rejects',async()=>{const bytes=await patch(await demoBytes(),'xl/_rels/workbook.xml.rels',s=>s.replace('Target="styles.xml"','Target="worksheets/sheet1.xml"'));await assert.rejects(importWorkbook(bytes),e=>e.code==='RELATIONSHIP')});
for(const [label,part,mutate]of [
 ['nested formula markup','xl/worksheets/sheet1.xml',s=>s.replace('<f>','<f><extLst><ext uri="test"/></extLst>')],
 ['nested cached value markup','xl/worksheets/sheet1.xml',s=>s.replace('<v>8</v>','<v>8<bogus>999</bogus></v>')],
 ['nested string markup','xl/worksheets/sheet1.xml',s=>s.replace('Workshop planning</t>','Workshop planning<bogus/></t>')],
 ['column extension','xl/worksheets/sheet1.xml',s=>s.replace('<col min="1" max="1" width="28" customWidth="1"/>','<col min="1" max="1" width="28" customWidth="1"><extLst/></col>')],
 ['font extension','xl/styles.xml',s=>s.replace('<font>','<font><extLst><ext uri="test"/></extLst>')],
 ['font unknown attribute','xl/styles.xml',s=>s.replace('<font>','<font unknown="true">')],
 ['undeclared attribute prefix','xl/worksheets/sheet1.xml',s=>s.replace('<sheetFormatPr ','<sheetFormatPr hacked:abc="1" ')],
 ['unbound r prefix','xl/workbook.xml',s=>s.replace(' xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"','')],
 ['plain unknown format attribute','xl/worksheets/sheet1.xml',s=>s.replace('<sheetFormatPr ','<sheetFormatPr unknown="1" ')],
 ['relationship nested extension','xl/_rels/workbook.xml.rels',s=>s.replace('Target="styles.xml"/>','Target="styles.xml"><unknown/></Relationship>')],
 ['manifest nested extension','[Content_Types].xml',s=>s.replace('Extension="xml" ContentType="application/xml"/>','Extension="xml" ContentType="application/xml"><unknown/></Default>')]
])test('recursive profile rejects '+label,async()=>{const bytes=await patch(await demoBytes(),part,mutate);await assert.rejects(importWorkbook(bytes),e=>['XML','FEATURE'].includes(e.code))});
test('XML depth budget applies before tree construction',async()=>{const nested='<bogus>'.repeat(65)+'x'+'</bogus>'.repeat(65),bytes=await patch(await demoBytes(),'xl/worksheets/sheet1.xml',s=>s.replace('</worksheet>',nested+'</worksheet>'));await assert.rejects(importWorkbook(bytes),e=>e.code==='XML_LIMIT')});
test('XML element budget applies before tree construction',async()=>{const bytes=await patch(await demoBytes(),'xl/worksheets/sheet1.xml',s=>s.replace('</worksheet>','<bogus/>'.repeat(100001)+'</worksheet>'));await assert.rejects(importWorkbook(bytes),e=>e.code==='XML_LIMIT')});
test('expanded repeated SUM visits are bounded before unique-edge deduplication',async()=>{const cells={};for(let i=1;i<=1000;i++)cells['A'+i]=1;cells.B1={formula:'SUM('+Array(100).fill('A1:A1000').join(',')+')'};issue(await wb([{name:'Plan',cells}]),['Plan'],'DEPENDENCY_WORK_LIMIT')});
test('repeated deep lineage is bounded before large evidence serialization',async()=>{const cells={A1:1};for(let i=2;i<=500;i++)cells['A'+i]={formula:'A'+(i-1)+'+1'};const w=await wb([{name:'Plan',cells:{A1:{formula:Array(100).fill('Other!A500').join('+')}}},{name:'Other',cells}]);issue(w,['Plan'],'EVIDENCE_LIMIT')});
for(const [name,offset,value,size]of [['method',8,0,2],['encryption',6,1,2],['unpacked size',22,1,4],['CRC',14,0,4]])test('ZIP central/local mismatch rejects '+name,async()=>{const bytes=await demoBytes(),v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);size===2?v.setUint16(offset,value,true):v.setUint32(offset,value,true);assert.throws(()=>inspectZip(bytes),e=>e.code==='ZIP');await assert.rejects(importWorkbook(bytes),e=>e.code==='ZIP')});
test('dishonest declared size is capped during actual streaming inflation',async()=>{const bytes=await demoBytes(),v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);let p=0;while(p<bytes.length-4&&v.getUint32(p,true)!==0x02014b50)p++;assert.ok(p<bytes.length-4);const local=v.getUint32(p+42,true);v.setUint32(p+24,1,true);v.setUint32(local+22,1,true);inspectZip(bytes);await assert.rejects(importWorkbook(bytes),e=>e.code==='ZIP_LIMIT')});
for(const [label,part,mutate,code]of [
 ['unused invalid column style','xl/worksheets/sheet1.xml',s=>s.replace('</cols>','<col min="7" max="7" style="999"/></cols>'),'STYLE'],
 ['empty row invalid style','xl/worksheets/sheet1.xml',s=>s.replace('</sheetData>','<row r="100" s="999" customFormat="1"/></sheetData>'),'STYLE'],
 ['column outside Excel bound','xl/worksheets/sheet1.xml',s=>s.replace('</cols>','<col min="20000" max="21000" width="15"/></cols>'),'COLUMN'],
 ['bad font cross reference','xl/styles.xml',s=>s.replace('fontId="0"','fontId="999"'),'STYLE'],
 ['bad fill cross reference','xl/styles.xml',s=>s.replace('fillId="0"','fillId="999"'),'STYLE'],
 ['duplicate address attribute','xl/worksheets/sheet1.xml',s=>s.replace('r="B2" s="2"','r="B2" r="D2" s="2"'),'XML'],
 ['duplicate type attribute','xl/worksheets/sheet1.xml',s=>s.replace('r="B2" s="2"','r="B2" s="2" t="n" t="b"'),'XML'],
 ['literal NUL','xl/worksheets/sheet1.xml',s=>s.replace('Workshop planning','Workshop\u0000planning'),'XML'],
 ['numeric NUL','xl/worksheets/sheet1.xml',s=>s.replace('Workshop planning','Workshop&#0;planning'),'XML'],
 ['unknown number format','xl/styles.xml',s=>s.replace('numFmtId="2"','numFmtId="888"'),'STYLE']
])test('strict XML/layout rejects '+label,async()=>{const bytes=await patch(await demoBytes(),part,mutate);await assert.rejects(importWorkbook(bytes),e=>e.code===code)});
test('unrecognized processing instructions reject',async()=>{const bytes=await patch(await demoBytes(),'xl/worksheets/sheet1.xml',s=>s.replace('<sheetData>','<sheetData><?xml-stylesheet href="x"?>'));await assert.rejects(importWorkbook(bytes),e=>e.code==='XML')});
test('valid stored and signed-descriptor ZIP packages import',async()=>{const {default:JSZip}=await import('jszip');for(const compression of ['STORE','DEFLATE']){const files=await readZip(await demoBytes()),zip=new JSZip();for(const [name,text]of files)zip.file(name,text,{createFolders:false});const bytes=await zip.generateAsync({type:'uint8array',compression,streamFiles:true});const a=analyze(await importWorkbook(bytes),['Plan']);assert.equal(a.ok,true);assert.deepEqual(a.preview.map(p=>p.value),[46,10,56]);}});

test('theme extensions are rejected recursively',async()=>{const files=await readZip(await demoBytes());files.set('xl/theme/theme1.xml',fs.readFileSync(new URL('../fixtures/default-theme.xml',import.meta.url),'utf8').replace('<a:latin ', '<a:latin unknown="1" '));files.set('[Content_Types].xml',files.get('[Content_Types].xml').replace('</Types>','<Override PartName="/xl/theme/theme1.xml" ContentType="application/vnd.openxmlformats-officedocument.theme+xml"/></Types>'));files.set('xl/_rels/workbook.xml.rels',files.get('xl/_rels/workbook.xml.rels').replace('</Relationships>','<Relationship Id="theme" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme" Target="theme/theme1.xml"/></Relationships>'));await assert.rejects(importWorkbook(await writeZip(files)),e=>e.code==='THEME')});
for(const [label,modify]of [
 ['numeric plus inline payload',s=>s.replace('<v>8</v>','<v>8</v><is><t>unexpected</t></is>')],
 ['formula plus inline payload',s=>s.replace('</f>','</f><is><t>unexpected</t></is>')],
 ['inline string plus numeric payload',s=>s.replace('</is>','</is><v>999</v>')]
])test('cell payload alternatives reject '+label,async()=>{const bytes=await patch(await demoBytes(),'xl/worksheets/sheet1.xml',modify);await assert.rejects(importWorkbook(bytes),e=>e.code==='CELL')});
test('duplicate custom numFmt IDs cannot override date detection',async()=>{const bytes=await patch(await demoBytes(),'xl/styles.xml',s=>s.replace('<fonts','<numFmts count="2"><numFmt numFmtId="164" formatCode="yyyy-mm-dd"/><numFmt numFmtId="164" formatCode="0.00"/></numFmts><fonts').replace('numFmtId="2"','numFmtId="164"'));await assert.rejects(importWorkbook(bytes),e=>e.code==='STYLE')});
test('style count mismatch rejects',async()=>{const bytes=await patch(await demoBytes(),'xl/styles.xml',s=>s.replace('<fonts count="2">','<fonts count="999">'));await assert.rejects(importWorkbook(bytes),e=>e.code==='STYLE')});
test('relationship prefix declared locally on sheet remains valid',async()=>{const bytes=await patch(await demoBytes(),'xl/workbook.xml',s=>s.replace(' xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"','').replaceAll('<sheet name=','<sheet xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" name='));const a=analyze(await importWorkbook(bytes),['Plan']);assert.equal(a.ok,true);assert.deepEqual(a.preview.map(p=>p.value),[46,10,56])});
test('plain openpyxl-produced workbook imports with local namespaces and empty protection container',async()=>{const w=await importWorkbook(new Uint8Array(fs.readFileSync(new URL('../fixtures/plain-openpyxl.xlsx',import.meta.url))));const a=analyze(w,['Plan']);assert.equal(a.ok,true);assert.equal(a.preview[0].value,48);assert.equal(a.preview[0].after,'=B2*(6)')});
test('active workbook protection still rejects',async()=>{const bytes=await patch(await demoBytes(),'xl/workbook.xml',s=>s.replace('</workbook>','<workbookProtection lockStructure="1"/></workbook>'));await assert.rejects(importWorkbook(bytes),e=>e.code==='FEATURE')});
test('blank row declarations have a workbook-wide budget',async()=>{const bytes=await patch(await demoBytes(),'xl/worksheets/sheet1.xml',s=>s.replace('</sheetData>',Array.from({length:10001},(_,i)=>`<row r="${i+100}"/>`).join('')+'</sheetData>'));await assert.rejects(importWorkbook(bytes),e=>e.code==='LAYOUT_LIMIT')});
test('column declaration count has a workbook-wide budget',async()=>{const bytes=await patch(await demoBytes(),'xl/worksheets/sheet1.xml',s=>s.replace('</cols>','<col min="4" max="4" width="10"/>'.repeat(1001)+'</cols>'));await assert.rejects(importWorkbook(bytes),e=>e.code==='LAYOUT_LIMIT')});
