import {DetachError} from './formula.mjs';
import {children} from './xml.mjs';
const spec=(attrs='',kids='',text=false)=>({attrs:attrs.split(' ').filter(Boolean),kids:kids.split(' ').filter(Boolean),text});
const color='auto indexed rgb theme tint';
// Deliberately narrower than OOXML. Every preserved node is checked recursively.
const schema={
 worksheet:spec('','sheetPr dimension sheetViews sheetFormatPr cols sheetData mergeCells pageMargins printOptions pageSetup'),
 sheetPr:spec('codeName filterMode published syncHorizontal syncVertical transitionEvaluation transitionEntry','tabColor outlinePr pageSetUpPr'),
 tabColor:spec(color),outlinePr:spec('applyStyles summaryBelow summaryRight showOutlineSymbols'),pageSetUpPr:spec('autoPageBreaks fitToPage'),dimension:spec('ref'),
 sheetViews:spec('','sheetView'),sheetView:spec('windowProtection showFormulas showGridLines showRowColHeaders showZeros rightToLeft tabSelected showRuler showOutlineSymbols defaultGridColor showWhiteSpace view topLeftCell colorId zoomScale zoomScaleNormal zoomScaleSheetLayoutView zoomScalePageLayoutView workbookViewId','pane selection'),
 pane:spec('xSplit ySplit topLeftCell activePane state'),selection:spec('pane activeCell activeCellId sqref'),
 sheetFormatPr:spec('baseColWidth defaultColWidth defaultRowHeight customHeight zeroHeight thickTop thickBottom outlineLevelRow outlineLevelCol'),
 cols:spec('','col'),col:spec('min max width style hidden bestFit customWidth outlineLevel collapsed'),sheetData:spec('','row'),row:spec('r spans s customFormat ht hidden customHeight outlineLevel collapsed thickTop thickBot ph','c'),c:spec('r s t','f v is'),f:spec('t ref si ca aca bx dt2D dtr del1 del2 r1 r2','',true),v:spec('','',true),is:spec('','t'),t:spec('xml:space','',true),
 mergeCells:spec('count','mergeCell'),mergeCell:spec('ref'),pageMargins:spec('left right top bottom header footer'),printOptions:spec('horizontalCentered verticalCentered headings gridLines gridLinesSet'),pageSetup:spec('paperSize scale firstPageNumber fitToWidth fitToHeight pageOrder orientation usePrinterDefaults blackAndWhite draft cellComments useFirstPageNumber errors horizontalDpi verticalDpi copies'),
 workbook:spec('','fileVersion workbookPr workbookProtection bookViews sheets calcPr definedNames'),fileVersion:spec('appName lastEdited lowestEdited rupBuild codeName'),
 workbookProtection:spec(),workbookPr:spec('date1904 dateCompatibility showObjects showBorderUnselectedTables filterPrivacy promptedSolutions showInk backupFile saveExternalLinkValues updateLinks codeName hidePivotFieldList showPivotChartFilter allowRefreshQuery autoCompressPictures checkCompatibility defaultThemeVersion'),bookViews:spec('','workbookView'),workbookView:spec('visibility minimized showHorizontalScroll showVerticalScroll showSheetTabs xWindow yWindow windowWidth windowHeight tabRatio firstSheet activeTab autoFilterDateGrouping'),sheets:spec('','sheet'),sheet:spec('name sheetId state r:id'),calcPr:spec('calcId calcMode fullCalcOnLoad refMode iterate iterateCount iterateDelta fullPrecision calcCompleted calcOnSave concurrentCalc concurrentManualCount forceFullCalc'),definedNames:spec('','definedName'),definedName:spec('name localSheetId hidden function vbProcedure xlm functionGroupId shortcutKey publishToServer workbookParameter','',true),
 sst:spec('count uniqueCount','si'),si:spec('','t'),
 styleSheet:spec('','numFmts fonts fills borders cellStyleXfs cellXfs cellStyles dxfs tableStyles colors'),numFmts:spec('count','numFmt'),numFmt:spec('numFmtId formatCode'),fonts:spec('count','font'),font:spec('','name charset family b i strike outline shadow condense extend color sz u vertAlign scheme'),
 name:spec('val'),charset:spec('val'),family:spec('val'),b:spec('val'),i:spec('val'),strike:spec('val'),outline:spec('val'),shadow:spec('val'),condense:spec('val'),extend:spec('val'),color:spec(color),sz:spec('val'),u:spec('val'),vertAlign:spec('val'),scheme:spec('val'),
 fills:spec('count','fill'),fill:spec('','patternFill gradientFill'),patternFill:spec('patternType','fgColor bgColor'),fgColor:spec(color),bgColor:spec(color),gradientFill:spec('type degree left right top bottom','stop'),stop:spec('position','color'),
 borders:spec('count','border'),border:spec('diagonalUp diagonalDown outline','left right top bottom diagonal vertical horizontal start end'),left:spec('style','color'),right:spec('style','color'),top:spec('style','color'),bottom:spec('style','color'),diagonal:spec('style','color'),vertical:spec('style','color'),horizontal:spec('style','color'),start:spec('style','color'),end:spec('style','color'),
 cellStyleXfs:spec('count','xf'),cellXfs:spec('count','xf'),xf:spec('numFmtId fontId fillId borderId xfId applyNumberFormat applyFont applyFill applyBorder applyAlignment applyProtection pivotButton quotePrefix','alignment protection'),alignment:spec('horizontal vertical textRotation wrapText shrinkToFit indent relativeIndent justifyLastLine readingOrder'),protection:spec('locked hidden'),cellStyles:spec('count','cellStyle'),cellStyle:spec('name xfId builtinId iLevel hidden customBuiltin'),dxfs:spec('count'),tableStyles:spec('count defaultTableStyle defaultPivotStyle'),colors:spec('','indexedColors mruColors'),indexedColors:spec('','rgbColor'),rgbColor:spec('rgb'),mruColors:spec('','color'),
 Types:spec('','Default Override'),Default:spec('Extension ContentType'),Override:spec('PartName ContentType'),Relationships:spec('','Relationship'),Relationship:spec('Id Type Target TargetMode')
};
export function validateProfileTree(root,context){let visited=0;const stack=[root];while(stack.length){const node=stack.pop();if(++visited>100000)throw new DetachError('XML_LIMIT',`XML element limit exceeded in ${context}`);const rule=schema[node.name];if(!rule)throw new DetachError('FEATURE',`Unsupported ${context} element: ${node.name}`);for(const name of Object.keys(node.attributes||{})){if(name==='xmlns'||name==='xmlns:r')continue;if(!rule.attrs.includes(name))throw new DetachError('FEATURE',`Unsupported ${node.name} attribute: ${name}`);}for(const c of children(node)){if(!rule.kids.includes(c.name))throw new DetachError('FEATURE',`Unsupported ${node.name} child: ${c.name}`);stack.push(c);}if(!rule.text&&(node.elements||[]).some(e=>(e.type==='text'&&e.text.trim())||(e.type==='cdata'&&e.cdata.trim())))throw new DetachError('FEATURE',`Unexpected text in ${node.name}`);}}
