import {xmlLexicalPreflight} from './xml-lexical.mjs';
import sax from 'sax';
import xmljs from 'xml-js';
import {DetachError} from './formula.mjs';
export const NS='http://schemas.openxmlformats.org/spreadsheetml/2006/main';
export const REL='http://schemas.openxmlformats.org/package/2006/relationships';
export function parseXml(text,path,{drawing=false}={}){if(/<!DOCTYPE|<!ENTITY|<\?[^x]/i.test(text))throw new DetachError('XML',`Unsupported XML declaration in ${path}`);try{xmlLexicalPreflight(text);let depth=0,count=0;const preflight=sax.parser(true,{xmlns:true});preflight.onopentag=()=>{if(++depth>64||++count>100000)throw new DetachError('XML_LIMIT',`XML depth/element limit exceeded in ${path}`);};preflight.onclosetag=()=>{depth--;};preflight.ondoctype=()=>{throw new DetachError('XML','DTD is unsupported');};preflight.onerror=e=>{throw e};preflight.write(text).close();const doc=xmljs.xml2js(text,{compact:false,ignoreComment:true,ignoreDeclaration:true});const roots=doc.elements?.filter(x=>x.type==='element')||[];if(roots.length!==1)throw Error('Expected one root');const root=roots[0],namespace=drawing?(root.attributes?.xmlns||root.attributes?.['xmlns:a']):root.attributes?.xmlns;const stack=[root];while(stack.length){const node=stack.pop();for(const [name,val]of Object.entries(node.attributes||{})){if(name.includes(':')&&!['xmlns:r','xmlns:a','xml:space','r:id'].includes(name))throw Error('Unsupported namespaced attribute');if(name==='r:id'&&!(root.attributes?.['xmlns:r']||node.attributes?.['xmlns:r']))throw Error('Unbound relationship prefix');if(name==='xml:space'&&!['preserve','default'].includes(val))throw Error('Invalid xml:space');if(name==='xmlns'&&val!==namespace)throw Error('Namespace rebinding is unsupported');if(name.startsWith('xmlns:')&&!((!drawing&&name==='xmlns:r'&&val==='http://schemas.openxmlformats.org/officeDocument/2006/relationships')||(drawing&&name==='xmlns:a'&&val==='http://schemas.openxmlformats.org/drawingml/2006/main')))throw Error('Unsupported namespace prefix');}if(drawing&&!node.name.includes(':')&&!root.attributes?.xmlns&&!node.attributes?.xmlns)throw Error('Unqualified DrawingML element');if(node.name.includes(':')&&!(drawing&&node.name.startsWith('a:')))throw Error('Prefixed elements are unsupported');if(drawing&&Object.keys(node.attributes||{}).some(x=>x.startsWith('r:')))throw Error('Theme relationships are unsupported');stack.push(...(node.elements||[]).filter(x=>x.type==='element'));}return root;}catch(e){if(e instanceof DetachError)throw e;throw new DetachError('XML',`Invalid XML in ${path}: ${e.message}`)}}
export function serialize(root){return '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'+xmljs.js2xml({elements:[root]},{compact:false,spaces:0});}
export const el=(name,attributes={},elements=[])=>({type:'element',name,attributes,elements});
export const txt=text=>({type:'text',text:String(text)});
export const children=(node,name)=>node?.elements?.filter(e=>e.type==='element'&&(!name||e.name===name))||[];
export const child=(node,name)=>children(node,name)[0];
export const value=node=>(node?.elements||[]).filter(e=>e.type==='text'||e.type==='cdata').map(e=>e.text??e.cdata).join('');
export const clone=obj=>JSON.parse(JSON.stringify(obj));
export function allow(node,names,context){for(const e of children(node))if(!names.includes(e.name))throw new DetachError('FEATURE',`Unsupported ${context} feature: ${e.name}`)}
