import JSZip from 'jszip';
import pako from 'pako';
import {DetachError} from './formula.mjs';
export const LIMITS=Object.freeze({sheets:20,cells:10000,formulas:2000,fileBytes:8*1024*1024,unpackedBytes:32*1024*1024,entries:100,rangeCells:10000,formulaCharacters:500000,formulaLength:8192,formulaNesting:128,dependencyEdges:100000,referenceVisits:100000,lineageWork:100000,evidenceUnits:50000,evidenceCharacters:8*1024*1024,styles:1000,merges:1000,maxAbsoluteValue:1e100,xmlDepth:64,xmlElements:100000,rowDeclarations:10000,columnDeclarations:1000,styleContainerEntries:1000});
const fail=(code,message)=>{throw new DetachError(code,message)};
export function inspectZip(input){
 const bytes=input instanceof Uint8Array?input:new Uint8Array(input);if(bytes.length>LIMITS.fileBytes)fail('FILE_LIMIT','XLSX exceeds 8 MiB');const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);let end=-1;
 for(let p=bytes.length-22;p>=Math.max(0,bytes.length-65557);p--)if(v.getUint32(p,true)===0x06054b50){end=p;break}
 if(end<0)fail('ZIP','Not a supported XLSX ZIP');const count=v.getUint16(end+10,true),size=v.getUint32(end+12,true),offset=v.getUint32(end+16,true);
 if(v.getUint16(end+4,true)||v.getUint16(end+6,true)||v.getUint16(end+8,true)!==count||count>LIMITS.entries||offset+size!==end)fail('ZIP','Unsupported multipart/ZIP64 package or entry limit');if(end+22+v.getUint16(end+20,true)!==bytes.length)fail('ZIP','Unexpected bytes after ZIP');
 let p=offset,total=0;const seen=new Set(),records=[],decoder=new TextDecoder('utf-8',{fatal:true});
 function extra(start,len){let q=start;while(q<start+len){if(q+4>start+len)fail('ZIP','Invalid extra field');const tag=v.getUint16(q,true),n=v.getUint16(q+2,true);if(tag===1||q+4+n>start+len)fail('ZIP','ZIP64 or malformed extra field');q+=4+n;}}
 for(let k=0;k<count;k++){
  if(p+46>end||v.getUint32(p,true)!==0x02014b50)fail('ZIP','Invalid directory');const flag=v.getUint16(p+8,true),method=v.getUint16(p+10,true),crc=v.getUint32(p+16,true),packed=v.getUint32(p+20,true),unpacked=v.getUint32(p+24,true),n=v.getUint16(p+28,true),ex=v.getUint16(p+30,true),comment=v.getUint16(p+32,true),disk=v.getUint16(p+34,true),local=v.getUint32(p+42,true);
  if(flag&~0x080e||![0,8].includes(method)||disk||[packed,unpacked,local].includes(0xffffffff)||p+46+n+ex+comment>end)fail('ZIP','Encrypted, ZIP64 or unsupported entry');let name;try{name=decoder.decode(bytes.subarray(p+46,p+46+n))}catch{fail('ZIP','Invalid UTF-8 ZIP path')}
  if(!name||name.startsWith('/')||name.includes('\\')||name.split('/').some(x=>x==='..'||x==='.')||seen.has(name))fail('ZIP','Unsafe or duplicate ZIP path');seen.add(name);extra(p+46+n,ex);total+=unpacked;if(total>LIMITS.unpackedBytes||unpacked>8*1024*1024)fail('ZIP_LIMIT','Unpacked XLSX exceeds profile limit');
  if(local+30>offset||v.getUint32(local,true)!==0x04034b50)fail('ZIP','Invalid local entry');const lf=v.getUint16(local+6,true),lm=v.getUint16(local+8,true),lc=v.getUint32(local+14,true),lp=v.getUint32(local+18,true),lu=v.getUint32(local+22,true),ln=v.getUint16(local+26,true),le=v.getUint16(local+28,true),dataStart=local+30+ln+le,dataEnd=dataStart+packed;
  if(lf!==flag||lm!==method||dataEnd>offset||local+30+ln+le>offset)fail('ZIP','Central/local metadata mismatch');let lname;try{lname=decoder.decode(bytes.subarray(local+30,local+30+ln))}catch{fail('ZIP','Invalid local path')};if(lname!==name)fail('ZIP','Local entry name mismatch');extra(local+30+ln,le);
  let localEnd=dataEnd;if(flag&8){if(![0,crc].includes(lc)||![0,packed].includes(lp)||![0,unpacked].includes(lu))fail('ZIP','Invalid descriptor-mode local sizes');const signed=dataEnd+4<=offset&&v.getUint32(dataEnd,true)===0x08074b50,desc=dataEnd+(signed?4:0);if(desc+12>offset||v.getUint32(desc,true)!==crc||v.getUint32(desc+4,true)!==packed||v.getUint32(desc+8,true)!==unpacked)fail('ZIP','Invalid data descriptor');localEnd=desc+12;}else if(lc!==crc||lp!==packed||lu!==unpacked)fail('ZIP','Central/local CRC or size mismatch');
  if(method===0&&packed!==unpacked)fail('ZIP','Stored entry size mismatch');if(name.endsWith('/')&&(packed||unpacked))fail('ZIP','Nonempty directory entry');records.push({name,method,crc,packed,unpacked,local,localEnd,dataStart,dataEnd});p+=46+n+ex+comment;
 }
 if(p!==end)fail('ZIP','Directory size mismatch');let next=0;for(const r of [...records].sort((a,b)=>a.local-b.local)){if(r.local!==next)fail('ZIP','Overlapping entries or unlisted local bytes');next=r.localEnd;}if(next!==offset)fail('ZIP','Unexpected bytes before central directory');return {bytes,total,entries:count,records};
}
const crcTable=Uint32Array.from({length:256},(_,n)=>{let c=n;for(let k=0;k<8;k++)c=c&1?0xedb88320^(c>>>1):c>>>1;return c>>>0;});
function crcChunk(crc,bytes){for(const b of bytes)crc=crcTable[(crc^b)&255]^(crc>>>8);return crc;}
export async function readZip(input){const {bytes,records}=inspectZip(input),files=new Map();let totalActual=0;for(const r of records){const chunks=[];let length=0,crc=0xffffffff;const consume=chunk=>{length+=chunk.length;totalActual+=chunk.length;if(length>r.unpacked||length>8*1024*1024||totalActual>LIMITS.unpackedBytes)fail('ZIP_LIMIT','Actual expanded ZIP bytes exceed declared/profile limits');crc=crcChunk(crc,chunk);chunks.push(chunk);};try{if(r.method===0)consume(bytes.subarray(r.dataStart,r.dataEnd));else{const inflater=new pako.Inflate({raw:true,chunkSize:16384});inflater.onData=consume;for(let pos=r.dataStart;pos<r.dataEnd;pos+=65536){const last=pos+65536>=r.dataEnd,accepted=inflater.push(bytes.subarray(pos,Math.min(pos+65536,r.dataEnd)),last);if(!accepted||inflater.err)fail('ZIP','Invalid deflate stream');if(inflater.ended&&(!last||inflater.strm.avail_in!==0))fail('ZIP','Trailing bytes in deflate stream');}if(!inflater.ended||inflater.err)fail('ZIP','Incomplete deflate stream');}if(length!==r.unpacked||((crc^0xffffffff)>>>0)!==r.crc)fail('ZIP','Expanded entry size or CRC mismatch');const content=new Uint8Array(length);let pos=0;for(const chunk of chunks){content.set(chunk,pos);pos+=chunk.length}if(!r.name.endsWith('/'))files.set(r.name,new TextDecoder('utf-8',{fatal:true}).decode(content));}catch(e){if(e instanceof DetachError)throw e;fail('ZIP',`Cannot decode ZIP entry: ${e.message}`)}}return files;}
export async function writeZip(files){const zip=new JSZip();for(const [name,text]of [...files].sort(([a],[b])=>a.localeCompare(b)))zip.file(name,text,{date:new Date('2000-01-01T00:00:00Z'),createFolders:false});return zip.generateAsync({type:'uint8array',compression:'DEFLATE',compressionOptions:{level:6},platform:'DOS'});}
